### PR TITLE
Preview Scheduled Content via Sidekick

### LINKED ISSUE #232: Preview Scheduled Content via Sidekick
* This is related to #140 and other areas where we support scheduled content.
* When previewing a page with the Sidekick, a user could select a date to preview the page at a certain point in time. All blocks on a page that use scheduled content could respect this date instead of the current date.
* For example you have an HTML block that is configured to show `pageA` until Wednesday and starting Thursday it shows `pageB`. When a user previews the page that contains the block on Tuesday, it will display `pageA`. When the user previews the page with the date set to Thursday, it should show `pageB`.

- [x] Develop a sidekick extension that allows to preview pages with a certain date set.
    - This feature should only be available for hlx.page, not for the live site.
- [ ] Update all content blocks that use scheduled content to respect the date set by the sidekick.

### PR DESCRIPTION
**Pull request by herzog31**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #232

For testing:
* You might need to run the branch locally and enable local Sidekick config, since Sidekick will not pick up a config from a branch.
* Go to https://issue-232--maidenform--hlxsites.hlx.page/drafts/mabecker/fragment-test
* Open sidekick and click on "Preview with date"
* Select a date between May 1-7 to see snippet 2.
* Select a date before May 1 to see snippet 0.
* Select a date after May 7 to see the homepage snippet.

This feature works for
* Banners
* Disruptors (PLP)
* HTML snippet block

Test URLs:
- Before: https://main--maidenform--hlxsites.hlx.page/
- After: 
    - https://issue-232--maidenform--hlxsites.hlx.live/
    - https://issue-232--maidenform--hlxsites.hlx.page/drafts/mabecker/fragment-test

### CODE REVIEW

**Comment by karigaron17** [comment]
@herzog31 
I do not see a 'preview with date' option in the plug-in. Does the plug-in need to be re-installed?
image

**Comment by herzog31** [comment]
@karigaron17 The steps are like this:
* Checkout the branch locally and run it (e.g. `npm run watch`).
* Go in the sidekick options, switch to "advanced" mode, edit the Maidenform project config and check "Test project configuration locally"
* Reload the page.

image

These steps are not required anymore when we merge this PR to the `main` branch.

**Comment by karigaron17** [comment]
This seems to be working. Only thing could maybe point out and it is very small is to maybe have the calendar open just under the 'preview with date' button. It took a moment to notice that it had opened at the bottom of the browser window. I run dark mode/theme and the banner being black it did not immediately stick out as a new element. 
image
Again supper small, nothing to hold this up.

**Review by karigaron17 — APPROVED** [review]

**Comment by herzog31** [comment]
@karigaron17 Thanks for the feedback. I moved it below the Sidekick button.

**Pull request merged**
