### PR TITLE
add keyboard and focus events to promo banner

### LINKED ISSUE #51: Promo Banner
The promo banner dose not have any method to allow the user to pause/stop the animation.
 - Users must have a method to pause/stop any animation or movement that auto plays. 
 
No method to select or navigate the slides previous or next.
- The slides auto rotate with no way to select the slide or go back. This makes it difficult for users to have time to read the banner and then potentially use any links or actions in the banner as the slide changes before interaction can be made. This is frustrating to users trying to use links when they slide away before can be activated.

Guideline: 2.2.2 Pause, Stop, Hide - Level A

### PR DESCRIPTION
**Pull request by hannessolo**
Fix #51 

Test URLs:
- Before: https://main--maidenform--hlxsites.hlx.page/block-library/blocks/promo-banner
- After: https://promo-banner-a11y--maidenform--hlxsites.hlx.page/block-library/blocks/promo-banner

### CODE REVIEW

**Review by herzog31 — APPROVED** [review]

**Comment by karigaron17** [comment]
Looks like clicking on the banner does stop the animation, it seems to be on a delay to re-start.
This would be better tied to a button that we can style to be pause/play icon.
This is a more intuitive method of functionality to a user. The user needs to have control to re-start is or not, this would also fix the the tabbing to the slider and ability to stop the animation from a keyboard. Arrow keys to move to next/prev is nice, but seems to start the animation. Again the toggle button should solve that issue.
Swipe to next or prev slide is good.

**Comment by hannessolo** [comment]
> ability to stop the animation from a keyboard

The pause is tied to focus on the banner, so it can also be paused by focusing the banner from the keyboard using tab. It won't continue playing until focus is lost.

> a button that we can style to be pause/play icon

That's a good idea, but might need to be deferred as it also needs some UI to be designed. Typically we first just take the existing UI and port it over to Franklin, and leave improvements such as this for later. Let's open a new issue to track this.

**Comment by karigaron17** [comment]
> The pause is tied to focus on the banner, so it can also be paused by focusing the banner from the keyboard using tab. It won't continue playing until focus is lost.

That is great, maybe I missed this due to difficulty knowing when the banner was focused.

I can help with the getting a UI for the pause/play button and an option with arrows approved for a new ticket. We can also look at adding a focus-visible and maybe even a focus-within on the banner as part of that work to help a user know when tabbed onto the banner.

The links with-in the banner had good visual focus.

**Comment by hannessolo** [comment]
Screenshot 2023-01-20 at 16 13 55

It's true that its hard to know when the banner is focused by clicking on it - if you you decide on a style we can add it. When tabbing to it in Firefox this blue outline is shown by the browser automatically, although not by clicking.

>  can help with the getting a UI for the pause/play button

Great! Please add your updates here: https://github.com/hlxsites/maidenform/issues/100 , and once you've decided on a style we can implement it.

**Pull request merged**
