### PR TITLE
Cart add

### LINKED ISSUE #317: Add-to-cart type: PDP
Need to add "addType" to cart additions on PDP

### PR DESCRIPTION
**Pull request by EmmyJordan**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #317 

Test URLs:
- Before: https://main--maidenform--hlxsites.hlx.page/
- After: https://cartAdd--maidenform--hlxsites.hlx.page/

### CODE REVIEW

**Comment by aniham** [comment]
@EmmyJordan   looks like you added `addType: 'pdp'` to the cart object. did you make any other changes?

**Comment by EmmyJordan** [comment]
Issues with addType being in all array elements so making a small change

**Comment by EmmyJordan** [comment]
@aniham There is only one location calling the add to cart function at this point. My original placement made it stuck in a loop and returned the value in triplicate so I have moved it.

**Comment by EmmyJordan** [comment]
@jokiser Please let me know when you can add from quick view and add from cart so I can add more types

**Comment by EmmyJordan** [comment]
@karigaron17

**Comment by EmmyJordan** [comment]
@herzog31 @hannessolo

**Review by herzog31 — APPROVED** [review]

**Pull request merged**
